### PR TITLE
#554 Optimized code ManifestActionImpl

### PR DESCRIPTION
**Pull request by TYzzt**
Cognitive Complexity of methods should not be too high

### CODE REVIEW

**Comment by TYzzt** [comment]
Hi @bjhargrave ,can you review my code,thanks

**Review by bjhargrave — COMMENTED** [review]
This does not appear to do anything other than rearrange the code into arbitrary methods. Reviewing this is low on my current priorities since it does not appear to add function or fix a bug. If it indeed optimizes the code (to run faster/smaller), can you provide any evidence?

**Comment by TYzzt** [comment]
Yes, it doesn't improve performance, but it does improve code maintainability

**Comment by bjhargrave** [comment]
Moving code into functions is useful to remove duplicate code. This just moves code into a function for a single call site. So it seems to waste time by creating a new stack frame to call a function which does what the single caller already does. So I don't see this change as valuable or useful. Thanks for trying but this change is not an improvement.

**Pull request closed without merging**
