### PR TITLE
Allow maven plugin to be used in a different artifact to the source

### LINKED ISSUE #139: Allow the transformed artifact to have it's own maven ID and runtime dependencies
If we have artifactA-1.0.jar which depends on artifactB-1.0.jar and transform them both then I get artifactA-1.0-transformed.jar and artifactB-1.0-transformed.jar. Great … but artifactA-1.0-transformed.jar still has a dependency on artifactB-1.0.jar. If the project that uses them declares a dependency on the two artifacts with the “transformed” classifier, it actually ends up pulling in both versions of artifactB.

This would be much clearer if the transformer operated in it's own maven project, with it's own artifact ID.
If the transformed artifact is completely separated from the original then it can also have a customized set of runtime dependencies.

At compile/package time...
artifactA-transformed-1.0 will depend on artifactA-1.0, which has a transitive dependency on artifactB-1.0.
artifactB-transformed-1.0 will depend on artifactB-1.0

At runtime, the dependencies will simply be...
artifactA-transformed-1.0 depends on artifactB-transformed-1.0

I have a working prototype that I will create a PR from.
I also note that there are some similar issues already open:
https://github.com/eclipse/transformer/issues/137 (@frantuma)
https://github.com/eclipse/transformer/issues/133 (@gitmotte)

### PR DESCRIPTION
**Pull request by tevans78**
fixes #139 
Signed-off-by: tevans <tevans@uk.ibm.com>

I'm not quite sure that I have the config right here. I also haven't found time to update the unit tests.
Hence why I am going to leave this as a draft PR for now. It will be a couple of weeks until I can come back to this.

The original pattern where an artifact in the same project is transformed will still work with what I have here except that the classifier is now optional. If not specified and the resulting ID clashes with the original then an exception is thrown.
e.g.
artifactA-1.0.jar -> artifactA-1.0.jar
or
artifactA1.0.jar -> artifactA-1.0-transformed.jar

The new configuration I have added means that the source artifacts can be taken from the project's dependencies. Instead of attaching the new artifacts to the project, they are set into it. i.e. is is assumed that there is nothing else in the target project.

Here is an example pom.xml where artifactA depends on artifactB. artifactB is transformed to become artifactA.
```
<project>
  <groupId>mygroup</groupId>
  <artifactId>artifactA</artifactId>
  <version>1.0</version>

  <dependencies>
    <dependency>
      <groupId>mygroup</groupId>
      <artifactId>artifactB</artifactId>
      <version>1.0</version>
      <scope>provided</scope> <!-- not transitive -->
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.eclipse.transformer</groupId>
        <artifactId>org.eclipse.transformer.maven</artifactId>
        <version>0.3.0-SNAPSHOT</version>
        <configuration>
          <attach>false</attach> <!-- I don't like the need for this -->
          <sourceArtifacts>
            <sourceArtifact>
              <groupId>mygroup</groupId>
              <artifactId>artifactB</artifactId>
              <version>1.0</version>
            </sourceArtifact>
          </sourceArtifacts>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>run</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

### CODE REVIEW

**Comment by tevans78** [comment]
@jgallimore Since you contributed the original plugin, I would like to get your feedback on these changes before going too much further?

**Comment by jgallimore** [comment]
@tevans78 Thanks for this. I'll take a look, I think it could be really useful for a use case I have.

**Comment by arjantijms** [comment]
I was recently looking at the exact same thing, and found this already to be largely implemented. @tevans78 any updates here?

**Comment by tevans78** [comment]
@arjantijms I am leaving this with @bjhargrave to decide on the best way to resolve these issues as a whole. Now would be a good time to comment on one of the already open issues ... or open a new one if nescesary.

**Comment by tevans78** [comment]
Seems to me that this will never be merged in its current state. Closing.

**Pull request closed without merging**
